# Generated by Django 3.1.3 on 2021-01-31 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Hotel', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=0, default=5, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15000)),
                ('main_image', models.ImageField(blank=True, upload_to='trips_pics')),
                ('image_one', models.ImageField(blank=True, upload_to='trips_pics')),
                ('image_two', models.ImageField(blank=True, upload_to='trips_pics')),
                ('image_three', models.ImageField(blank=True, upload_to='trips_pics')),
                ('image_four', models.ImageField(blank=True, upload_to='trips_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
