# Generated by Django 3.1.3 on 2021-02-02 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='deadline1',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 2)),
        ),
        migrations.AddField(
            model_name='trip',
            name='deadline2',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 2)),
        ),
        migrations.AddField(
            model_name='trip',
            name='deadline3',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 2)),
        ),
    ]
