# Generated by Django 3.1.3 on 2021-02-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210202_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='deadline1',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='deadline2',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='deadline3',
            field=models.DateField(blank=True),
        ),
    ]
