# Generated by Django 3.1.3 on 2021-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210202_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True)),
                ('trip', models.TextField(blank=True)),
                ('day', models.TextField(blank=True)),
                ('adults', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('kids', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guide', models.BooleanField(default=0)),
                ('room', models.BooleanField(default=0)),
            ],
        ),
    ]
