# Generated by Django 3.1.2 on 2021-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
