# Generated by Django 3.1.2 on 2021-02-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_trip_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.TextField(blank=True),
        ),
    ]
