# Generated by Django 3.1.2 on 2021-02-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_trip_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameAndLastName', models.TextField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Telephone', models.TextField(max_length=15)),
                ('Thema', models.TextField(max_length=50)),
                ('Content', models.TextField(max_length=500)),
            ],
        ),
    ]
